In [1]:
import psycopg2
import pickle
from sklearn.preprocessing import MinMaxScaler
import pandas as pd
import numpy as np

In [2]:
def load_model():
    from keras.models import load_model
    model = load_model("model1.keras")
    return model

In [3]:
db = 'postgresql://stock_price_g9q6_user:NxjC5lOyzg5HJftmjj49JUpYxLquARBl@dpg-d59ul99r0fns7381saug-a.singapore-postgres.render.com/stock_price_g9q6'

In [4]:
conn = psycopg2.connect(db)
conn.autocommit = True
my_cursor = conn.cursor()
my_cursor.execute('Select * from price_sentiment')
result = my_cursor.fetchall()
data = pd.DataFrame(result, columns = ['Date', 'Open', 'High', 'Low', 'Close', 'Volume', 'Dividends', 'Stock_Splits', 'Score', 'Positive' , 'Negative', 'Neutral', 'Total_Sentiment'])
data.set_index('Date', drop=True,inplace=True)
data.drop(['Open', 'High', 'Low', 'Dividends', 'Stock_Splits', 'Score', 'Positive' , 'Negative', 'Neutral'], inplace=True, axis=1)
data.sort_index(inplace=True)
scaler = MinMaxScaler(feature_range=(0,1))
data_scaled = scaler.fit_transform(data.iloc[-14:,])
input_data = data_scaled[-14: ,].reshape(1,14,3)
model = load_model()
prediction = model.predict(input_data)

arr = [prediction.flatten()[0],  prediction.flatten()[0], prediction.flatten()[0]]

arr = np.array(arr).reshape(1,-1)

y_pred_future = scaler.inverse_transform(arr)[0][0]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 322ms/step


In [5]:
arr

array([[0.75314677, 0.75314677, 0.75314677]], dtype=float32)

In [6]:
data.shape

(1813, 3)

In [7]:
data.tail()

Close       Volume  Total_Sentiment
Date                                             
2025-12-24  188.610   65528500.0         4.750000
2025-12-26  190.530  139740300.0         5.000000
2025-12-29  188.220  119715400.0         9.958333
2025-12-30  187.385   19847520.0         1.000000
2025-12-31  186.500  120100496.0        13.956522

In [11]:
for i in range(len(data)-n_past*2 , len(data)-14):
    print(data.iloc[i:i+14,:])

                Close       Volume  Total_Sentiment
Date                                               
2025-11-20  180.62994  343504800.0        50.876290
2025-11-21  178.87004  346926200.0         4.696969
2025-11-24  182.53984  256618300.0         7.814815
2025-11-25  177.81010  320600300.0         6.555555
2025-11-26  180.24995  183852000.0        10.793103
2025-11-28  176.99014  121332800.0         3.866667
2025-12-01  179.90999  188131010.0        13.968750
2025-12-02  181.44990  182632190.0         2.842105
2025-12-03  179.58000  165138000.0         8.740741
2025-12-04  183.38000  167364900.0         3.850000
2025-12-05  182.41000  143971100.0         3.846154
2025-12-08  185.55000  204378100.0         8.950000
2025-12-09  184.97000  144719700.0        11.685715
2025-12-10  183.78000  162785410.0         0.708333
                Close       Volume  Total_Sentiment
Date                                               
2025-11-21  178.87004  346926200.0         4.696969
2025-11-24  

In [12]:

scaler_new = MinMaxScaler(feature_range=(0,1))
#datafortrain = data[-28:,]

n_past = 14

traindata = []

for i in range(len(data)-n_past*2 , len(data)-14):
    traindata.append(scaler_new.fit_transform(data.iloc[i:i+14,:]))

In [ ]:
# n_past = 14

# traindata = []

# for i in range(len(data)-n_past*2 , len(data)-14):
#     traindata.append([data.iloc[i:i+14,:]])

In [ ]:
#traindata = np.array(traindata).reshape(14,3)

In [14]:

model = load_model()
prediction = model.predict(np.array(traindata).reshape(14,14,3))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 204ms/step


In [ ]:
prediction = prediction.flatten()

In [15]:
prediction

array([[0.5225524 ],
       [0.63150316],
       [0.7222142 ],
       [0.6741062 ],
       [0.66727716],
       [0.7469184 ],
       [0.6660988 ],
       [0.62743115],
       [0.624795  ],
       [0.52167475],
       [0.5759302 ],
       [0.5922867 ],
       [0.6530513 ],
       [0.72011906]], dtype=float32)

In [21]:
prediction[2]

array([0.7222142], dtype=float32)

In [24]:
arr= []
for i in range(0, len(prediction)):
    arr.append([prediction[i], prediction[i], prediction[i]])

In [38]:
np.array(arr).shape

(14, 3, 1)

In [31]:
np.array(arr).reshape(14,3)

array([[0.5225524 , 0.5225524 , 0.5225524 ],
       [0.63150316, 0.63150316, 0.63150316],
       [0.7222142 , 0.7222142 , 0.7222142 ],
       [0.6741062 , 0.6741062 , 0.6741062 ],
       [0.66727716, 0.66727716, 0.66727716],
       [0.7469184 , 0.7469184 , 0.7469184 ],
       [0.6660988 , 0.6660988 , 0.6660988 ],
       [0.62743115, 0.62743115, 0.62743115],
       [0.624795  , 0.624795  , 0.624795  ],
       [0.52167475, 0.52167475, 0.52167475],
       [0.5759302 , 0.5759302 , 0.5759302 ],
       [0.5922867 , 0.5922867 , 0.5922867 ],
       [0.6530513 , 0.6530513 , 0.6530513 ],
       [0.72011906, 0.72011906, 0.72011906]], dtype=float32)

In [32]:
predicted_price = scaler.inverse_transform(np.array(arr).reshape( 14,3))

In [33]:
predicted_price


array([[1.8117680e+02, 1.7926694e+08, 7.6510992e+00],
       [1.8331114e+02, 2.1250547e+08, 9.0899601e+00],
       [1.8508817e+02, 2.4017946e+08, 1.0287938e+01],
       [1.8414574e+02, 2.2550274e+08, 9.6525984e+00],
       [1.8401196e+02, 2.2341934e+08, 9.5624104e+00],
       [1.8557214e+02, 2.4771616e+08, 1.0614194e+01],
       [1.8398888e+02, 2.2305986e+08, 9.5468483e+00],
       [1.8323137e+02, 2.1126320e+08, 9.0361834e+00],
       [1.8317973e+02, 2.1045896e+08, 9.0013695e+00],
       [1.8115962e+02, 1.7899920e+08, 7.6395092e+00],
       [1.8222246e+02, 1.9555136e+08, 8.3560343e+00],
       [1.8254291e+02, 2.0054138e+08, 8.5720472e+00],
       [1.8373328e+02, 2.1907936e+08, 9.3745365e+00],
       [1.8504712e+02, 2.3954027e+08, 1.0260268e+01]], dtype=float32)

In [34]:
print(predicted_price[0][0])

181.1768
